project:
  type: website
  output-dir: docs

website:
  title: "Programming and Data Analysis with R"
  site-url: "https://thiyangt.github.io/rprogramming/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

