---
title: "STA 326 2.0/ ASP 454 2.0 Programming and Data Analysis with R"
---

## Lecturer-in-charge

[Dr Thiyanga S. Talagala](https://thiyanga.netlify.app/)

## Email

ttalagala\@sjp.ac.lk

## Policies and regulations

To access important information regarding the unit, please join the Google Classroom. You must carefully read the “[Course Information](https://hellor.netlify.app/2021/week0onsite#1)” slide set for essential details. It is your responsibility to be aware of important details by thoroughly reviewing the “Course Information” slides.

## Course outline

Available on Google Classroom

## Weekly schedule: Lectures 👩‍🏫

```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(tidyverse)
wkno <- c(1, 2, 3, 4, 5)
date <- c("April 23, 2026", "April 30, 2026", "May 7, 2026", "May 14, 2026", "May 21, 2026/May 28, 2026")
Topic <- c("[Introduction to R Programming](https://hellor.netlify.app/2021/week1/l12021#1)", "[Data Structures in R: Vector creation](https://hellor.netlify.app/slides/l22021#1)",
           "[Built-in functions in R: Anatomy](https://hellor2023.netlify.app/slides/l32021#1)",
           "[Working with built-in functions in R](https://hellor.netlify.app/slides/l42022#1)-removed qplot (qplot() is now deprecated)",
           "[User-defined functions](https://hellor.netlify.app/slides/l52021#1)")
cheatsheet <- c("[cheatsheet](https://hellor.netlify.app/cheatsheets/baser.pdf)", "", "", "", "")
reading <- c("", "", "", "", "")
exercise <- c("[Exercise 1.8]( https://thiyangt.github.io/rbook/intro.html)", "", "", "", "")
df <- tibble(wkno, date, Topic, cheatsheet,reading, exercise)
colnames(df) <- c("Week No.", "Date", "Topic", "Cheatsheet", "Reading", "Exercise"
                  )
df |> knitr::kable()
```

**June 4, 2026**

[Control Structures](https://hellor.netlify.app/slides/l62021#1)

**June 11, 2026**

[Introduction to the tidyverse](https://hellor.netlify.app/slides/l72021#1)

**June 18, 2026**

[tidy verbs](https://hellor.netlify.app/slides/l102021#1)

[dplyr verbs](https://hellor.netlify.app/slides/l112021#1)

[Introduction to ggplot2](https://hellor.netlify.app/slides/l122021#1)

**June 22, 2026**

[Introduction to quarto](/quarto/index.qmd)

**July 9, 2026**

Mid-semester Examination

**July 16, 2026**

[Regression Analysis](https://hellor.netlify.app/slides/l132021#1)

## Mid-Semester Examination

July 9, 2026

Content: From April 23, 2026 to May 21, 2026 (May 21, 2026 lecture included)

You are allow to bring 1 A4 sheet to the exam only.

## Weekly schedule: Computer Practical 🖥️

-   Monday, 8am - 9.45am

-   Monday, 3pm - 5pm

-   Please do not swap your allocated slots. Kindly attend at your stipulated time.

```         
```

## R and RStudio Installation: Video Links

[Installing R](https://www.youtube.com/watch?v=aRwxsAEoRzs&list=PL7Bw8wPdOZXlEVRbvYmP59SapfjfOy5pS&index=1)

[Installing RStudio](https://www.youtube.com/watch?v=Q1NRj2Dzdn0&t=18s)
